apiVersion: apps/v1
kind: Deployment
metadata:
  name: karma
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: karma
  template:
    metadata:
      labels:
        app.kubernetes.io/name: karma
    spec:
      containers:
        - name: karma
          image: ghcr.io/prymitive/karma:v0.125
          imagePullPolicy: IfNotPresent
          args:
            - --config.file=/etc/karma/karma.yaml
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: karma
              mountPath: /etc/karma
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
            requests:
              memory: 64Mi
              cpu: 50m
      volumes:
        - name: karma
          configMap:
            name: karma
