apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - gatewayclass.yaml
  - gateway.yaml
  - gateway-public.yaml
  - certificate.yaml
  - wildcard-tls.enc.yaml
