apiVersion: apps/v1
kind: Deployment
metadata:
  name: ca-download
  namespace: ca-download
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ca-download
  template:
    metadata:
      labels:
        app: ca-download
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: ca-cert
          mountPath: /usr/share/nginx/html
      volumes:
      - name: ca-cert
        configMap:
          name: ca-cert