apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ca-download
  namespace: ca-download
  annotations:
    external-dns.alpha.kubernetes.io/target: "k8s-lb-01.crulabs.intern"
spec:
  ingressClassName: nginx
  rules:
  - host: ca.crulabs.intern
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ca-download
            port:
              number: 80