apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:d/3ySK0=,iv:Q/N9OJR3MQO0ARQFjoihDm1WUjqaYsmql28fSIiFJWc=,tag:LuaCo0r/Q0ZX/cnuCmUKmw==,type:str]
    admin-password: ENC[AES256_GCM,data:Z2ef1a1lQ1m2ErZUrmE=,iv:Uee9/AKoSnQz3BUU8PuppNyu8Me855awDhakkRw+Dcw=,tag:pjZd/GCmI6YIVmyHpuCNyQ==,type:str]
sops:
    lastmodified: "2025-11-22T19:07:52Z"
    mac: ENC[AES256_GCM,data:N+ARklr2Cf16Nku/iPesZAU+xedQl4HGmODXlvP4EByXHQWUJTIPXqNSPOEAfhrc+WlJm0wa2ci2acW2wOveizGaOQvxVLsmTtsmfZRT6UffkS0fBlbt5t91ioo87mTL4NSG+94dQXru7xrT3TK5p8qLv21NLIqH0cRlwVfSSvA=,iv:go3cYjNI2UMXBH+9iIAV+UapKiYHu682tTmTK9gNgSE=,tag:Dn1b/8FuT2oZpHb6uQQJAQ==,type:str]
    pgp:
        - created_at: "2025-11-22T19:07:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0FBPlwYR03bARAAptnYqJ6cT4PriRWVmPgbA8q5y6NfWiMiBFe2nkA9tl+p
            u1uhXUag2AI7bj3b/2prJMWeKD7TV0x4ZIIqpi8jJzTDqkqiRT/u3vX2Ca9r+Ugm
            SnCt08OJ7oHifzg2Gw4v+Fg1cZVe19VO0vraZ6e5m5AIy2QPNfXyjNT9b4skFOT2
            9oIk6MypVrUnWq2pmUzSm/HjR0bvMBxPxH8Vbvc+GgF/GCsGj7rLkpZ7nan094zv
            Pwtr/3E4+aVe2Wtj62m7N6x2voJkF1pcnruAWkrEcPfIaIPKwFN9oNc3ag2chEdD
            6miOysYw6AvPbswXhMEkIJwaaLH7VmWWyrPLy9/XTgUCnjfI04QfAPMCooupBGiC
            0MeBwD3AbbBQOctiBZnGdtErN2WUvsGJGG4J2Js7a6mtPmNZgFtcJIlTvmDwwkrs
            NuebKdzqqiO/X1zDEgLUd581aLNSKbT7mPTYfEB0o8qpvZgGwONsM5LTIf49r91Z
            vf39wH41OQka2i60nX1WxdOBOjaINLhVTabOJod1uHVUt8JWxLl3+mC6ms5namCb
            fP61lz4z39v2vZuzbGYDIy03k4exwlX/ezkmGxiAIN6xMw4sbJlWGDlLUCN7SGjL
            QDhHsC6ryaA0CRVOg6fZmXkV7RltHoEu08fnQ+JW8MHnQGgOYip/d3CAMuqrTA3U
            ZgEJAhB64+7a3pmF/00C+2vFRpDSq/Q2wnfq1TDPMlZKVUHyN1HYzQ7fUzU4+bJP
            p3+JVyrbFVF86IzZdicYU+GmEpLIvZDUItvhjbpC34KV/TM8DgNGp71aLIBuoWWo
            27dhsOTpYA==
            =+Oz3
            -----END PGP MESSAGE-----
          fp: 2F45BC42327907C5B833A93041413E5C18474DDB
    encrypted_regex: ^(data|stringData|addresses)$
    version: 3.11.0
