apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 81.6.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  valuesFrom:
  - kind: ConfigMap
    name: flux-kube-state-metrics-config
    valuesKey: kube-state-metrics-config.yaml
  values:
    crds:
      enabled: true

    grafana:
      enabled: true
      admin:
        existingSecret: grafana
        userKey: admin-user
        passwordKey: admin-password
      defaultDashboardsEnabled: true
      ingress:
        enabled: false
      envFromSecret: grafana
      extraVolumes:
        - name: ca-cert
          configMap:
            name: crulabs-ca-cert
      extraVolumeMounts:
        - name: ca-cert
          mountPath: /etc/ssl/certs/crulabs-ca.crt
          subPath: ca.crt
          readOnly: true
      grafana.ini:
        server:
          root_url: https://grafana.crulabs.intern
        auth.generic_oauth:
          enabled: true
          name: Keycloak
          allow_sign_up: true
          auto_login: false
          client_id: $__env{CLIENT_ID}
          client_secret: $__env{CLIENT_SECRET}
          scopes: openid email profile
          email_attribute_path: email
          login_attribute_path: preferred_username
          name_attribute_path: full_name
          groups_attribute_path: groups
          id_token_attribute_name: preferred_username
          use_pkce: true
          auth_url: https://keycloak.crulabs.intern/auth/realms/crulabs/protocol/openid-connect/auth
          token_url: https://keycloak.crulabs.intern/auth/realms/crulabs/protocol/openid-connect/token
          api_url: https://keycloak.crulabs.intern/auth/realms/crulabs/protocol/openid-connect/userinfo
          role_attribute_path: contains(groups[*], 'admin') && 'Admin' || contains(groups[*], 'editor') && 'Editor' || 'Viewer'
          skip_org_role_sync: false
          tls_skip_verify_insecure: false
          tls_client_ca: /etc/ssl/certs/crulabs-ca.crt
          allow_assign_grafana_admin: true
        database:
          type: postgres
          host: grafana-postgres.monitoring.svc.cluster.local
          port: 5432
          name: grafana
          user: $__env{username}
          password: $__env{password}
          
      sidecar:
        dashboards:
          enabled: true
          label: grafana_dashboard
          folder: /var/lib/grafana/dashboards/custom
        datasources:
          enabled: true
          label: grafana_datasource
      additionalDataSources:
        - name: Loki
          type: loki
          access: proxy
          url: http://loki-gateway.loki.svc.cluster.local
          jsonData:
            maxLines: 1000
          isDefault: false
          editable: true

    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: local-path
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 50Gi
        retention: 90d
        additionalScrapeConfigs:
          - job_name: 'node-exporter'
            honor_labels: true
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
                action: keep
                regex: prometheus-node-exporter
              - source_labels: [__meta_kubernetes_pod_node_name]
                target_label: node
              - source_labels: [__address__]
                target_label: instance
        podMonitorSelector: {}
        podMonitorNamespaceSelector: {}
        podMonitorSelectorNilUsesHelmValues: false
        ruleNamespaceSelector: {}
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        serviceMonitorNamespaceSelector: {}
        serviceMonitorRelabelings:
          - sourceLabels: [__meta_kubernetes_node_name]
            targetLabel: node

    kubeScheduler:
      enabled: false
    kubeControllerManager:
      enabled: false
    kubeProxy:
      enabled: false
