apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - secret_grafana.enc.yaml
  - configmap_ca-cert.yaml
  - helmrelease_kube-prometheus-stack.yaml
  - helmrelease_postgres.yaml
  - httproute.yaml

configMapGenerator:
  - name: flux-dashboards
    namespace: monitoring
    files:
      - control-plane.json=dashboards/control-plane.json
      - cluster.json=dashboards/cluster.json
      - logs.json=dashboards/flux-logs.json
    options:
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
        kustomize.toolkit.fluxcd.io/substitute: disabled
  - name: shelly-dashboards
    namespace: monitoring
    files:
      - shelly-plug.json=dashboards/shelly-plug.json
    options:
      labels:
        grafana_dashboard: "1"
  - name: flux-kube-state-metrics-config
    namespace: monitoring
    files:
      - kube-state-metrics-config.yaml
    options:
      labels:
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring

generatorOptions:
  disableNameSuffixHash: true

configurations:
  - kustomizeconfig.yaml
