apiVersion: v1
kind: Secret
metadata:
    name: grafana
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:u9QTQZg=,iv:GmyNIPE2GbrNYZwWVy4f6Ucy1iZmcz6xDF5LS0t5LPs=,tag:/PqhVxpr59or8mljGo3RQA==,type:str]
    admin-password: ENC[AES256_GCM,data:sIcknjQefSo5jFJD8Ng=,iv:4n78asFnJ6vbhlqx1weBli9wnX2Px2pLxfcBJAwMlE0=,tag:2inu3FUhJTBcqGJ8n1NqVg==,type:str]
    GRAFANA_DB_USER: ENC[AES256_GCM,data:P3rS,iv:PtqMhQvjB+ykdZ+OvOA0e92lXQra6qhaGtrLH0dcDb4=,tag:ARt/s5+cyIgMJLAYzyQWqw==,type:str]
    GRAFANA_DB_PASSWORD: ENC[AES256_GCM,data:8HyeKkP2TWD4t6nHSTyphgHFvrcxw4IFVklD2bCF,iv:yTG5xC4vdH/MUfikSzwCDP1BGgFWEJtq64oIjiEeAPw=,tag:mhZamWd3ccE7q/x0LkuUYA==,type:str]
    CLIENT_ID: ENC[AES256_GCM,data:fk7G4OEzAw==,iv:U+3TBAgDZiZ8nxhfqoaIhdYhgXEr4zenpZtqI7VjhNg=,tag:6Ud0W5xqoSnZupuRNOdyQQ==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:5jgYe2AEdHM3KF4h421h/UZFxNZVBXlAW5mYeWymlnc=,iv:mxG644JbFpcTDUFep6TJNl6mvw2O4svQ5ELn5hATtqA=,tag:etM4R9rZTcoO5JjPDUrwCQ==,type:str]
sops:
    lastmodified: "2026-02-10T19:28:04Z"
    mac: ENC[AES256_GCM,data:xAM/AnIyk9YlpKgivM4fGvbJVWVULkOYJTJ18Bsv1wm5ujkL0Yg7VLG2HmMyrhJy5jsCOdqC9EzFaMaSPhlz9hctKZU02SCb6++wD/3rGBWm3n7QeZ6BlpOjyp38yDfcsqMSbOY93VMpIOEpl7nw79GmBV4mZdsOMczdwzJmKDc=,iv:EsxlKxi25hNmCdlfbrY//FOnd3iMx0fkmfjci5LoIVQ=,tag:Rn4rh4Tb4ba8hioogTbPvQ==,type:str]
    pgp:
        - created_at: "2026-02-10T19:28:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0FBPlwYR03bAQ//d5rVboQzY0VmsZrLVNh77bWnKNQNH51zdyFOJn7joYsG
            03seLTQMcIZaHAg7sJ3ekZh11Wv8HroctEij8EUfGlR6lQSQoY/QX1OeFevl1XHM
            B0uH2a1ojPrgXx1+NPPPK7E913cDnMx5Zfjy1P4gtb0/U8duSdvehRks0EriuFV5
            hg47TnK9jtEsl2hgRVkLQvPmE/IMfAiBkykr/dDACY3HNUX+BCqFTd4pb4fqAnAD
            e7KyduJPq7GFCl3eBKo+sDQclcAhkVazeJX9bRf/pCcKqHcNfXsIuyNoGjWI/4OG
            nz+WhZoMCtsu45Di6RFX6MjnTxmYXpLF9vl6uLfZRbeWXzDB2V/S15oFLhAyP4Ul
            M/3Jb9B6K7NC76nFkvIsYEynTYgjsmESr7NOUyrOWwtyZ/aFaMSbd1yqVQ2fOZCi
            7GhJnYy9sHAmpPa/FokJ3A7e96CLX+0zLNl0+CUrY1pgInmWEFMclY8vqYkPBPPG
            doizO6jaAydysvAzHatbHlTR9nbrJF9Rh28KM8rGz4G4IhLy9M5yungBGl6KloRy
            giHJBvh3QIrIunNYEqk5yvNPviYLJCv6r16uhJ0kSQegZ3nHYglRyO5D9RyR6lEN
            ALOlH/O5ohzrWJGWodvZi5/x9S+ceqB6t9q4O5xSzOl20yO2R89XVIp7CyikKYDU
            aAEJAhCdj2uSgE/lx1B14qSoXQjKgvAW80Xmv2VeoQd3nMRVt9oD82uBkmDkEFCo
            wyW/qYkLW4iIT03EFtEV35lXPuLYFKkZIVV5zLquLLWB6hAyYsBqk+Atdqj7WPLw
            wSnEhU+CLHVA
            =1KAL
            -----END PGP MESSAGE-----
          fp: 2F45BC42327907C5B833A93041413E5C18474DDB
    encrypted_regex: ^(data|stringData|addresses)$
    version: 3.11.0
