apiVersion: v1
kind: Secret
metadata:
    name: grafana
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:NwV1kxc=,iv:r+6dJnJsEv+kGJKh/bhAztohlE5B9KUT3N1fWWdVBH8=,tag:oCOOh0ua9gpov8JAU3dBoA==,type:str]
    admin-password: ENC[AES256_GCM,data:gd0Jr0IlZ36BvOoMujk=,iv:jP2xZoJcMLj0Dxi/kilhNuqEf5F6nTKgb7KIo82V1Ts=,tag:r8FGySeoS8SRM+t3duvJZA==,type:str]
    username: ENC[AES256_GCM,data:uWBQ,iv:Pf+xzlFTJ9k0HIxjoTqpY8xQgHE6XH46fnHmE6tS+Vk=,tag:lTPfRQE+0vx6knbgfaKQ4Q==,type:str]
    password: ENC[AES256_GCM,data:mzMF8vnqtiIZXzP2Cf6qjsVdZswG4nIsw2i95+cv,iv:jWG3GcjXSjqnx1UrXnE30C1y4pN4RdvJh69StTKlEr4=,tag:svOLCIls0k98FXk0iM8ZEg==,type:str]
    CLIENT_ID: ENC[AES256_GCM,data:Fe+jzmtPSQ==,iv:XMt0plMD9e5NhKDL9TmI63hAhJr+2ejN5djM0jl3Rmw=,tag:4jywJoyHftA1OJV/SbFSPg==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:vAbeBwv41W4ET9K1rRsNUOw4ZLig8VhrFmzsLP0jAfc=,iv:Wva7uO3x1Ay+6uADl/yC4BMHvmBk0M6Ks7SNGBpMxOE=,tag:r/5b/wPVmnW7p5v6vnPW2A==,type:str]
sops:
    lastmodified: "2026-02-10T19:43:18Z"
    mac: ENC[AES256_GCM,data:rwzgrRdXgI/8cPN8xX/PIZNBRBhm+ufd79mCWbiNL8+MJTzz3i1BSyc0K1GXE0NiFR71JEv67icuutlI+YDgP10HdzZTuyvXgCRBtg8rR/sLFD2UsOYz1NCy+/bOlhndA1xmsXOnACqsvPLqJ6ZI5P7rIMEYSnsLrKjtlEU0cY8=,iv:xT9EVgd75AXosmV7LzMgDA2Qz+YRPYY5u/eC4rWpZPI=,tag:wH+czXfZQPDs6O9AFM/vUw==,type:str]
    pgp:
        - created_at: "2026-02-10T19:43:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0FBPlwYR03bAQ/9FzDvVOEIb4TsF5EcSCLXUGyHZTlRlwZjg0XxYHNkZcfT
            Op22E34qNgty8EBLxJWxfF8Vs0c2YNJnPlFT2XtYI8RZjtRfRqKcc3pV8Sx7MTKz
            FQw5F3HDLk5hjyMLKY9Laxaa1lFLYtWP9BjJE4q/fDMEHG1cpgO2qZjm/NIuAK9h
            KQ9+64W8DMav5kp/3/k3QNncGhIyf08yjHvpYgQBlRVSrZyvHhBNGVQPa5kiztJ2
            16TsXF8MQkWONF7EQ7GuSIJHMl6SLNyFZMJcMeug3QtCiEoCiPdW8LbO7zqfVUEz
            S6Zj9VlgYKJwrc9ep3/c9viiqVaLzdGm3tLGcqLxFSO724yYoaupTmYLptBNJfoX
            QJcsdjtT1tlQPeHvnx5kmg78fTKxXMk4cg4qvTjYV8KiLH1X86khjJdb8jdCG/Is
            NJD6/1Swkb7PjLAYCJ8dHrYG3Xz90HQT8YTnaLz5GmpD2zmjjLTTvfWm4V5BG4r+
            GuW7WxBy92a1zjWYAcDWlBUsuP0zhOb73THsuExsthNfsfYtna72H37c0bI3sjQt
            oaG2itUdKMViVuZIde7L9BYsVMhXzCRPqra9c4sKyoEcY6gIEQGxUsaMx8kM55pF
            IXxd8sX0tUlSEnZPQ0sBupoPMUPyPhf2lj4naKjQltVpQ0vgfuvz3/IVOT2pXaDU
            aAEJAhD7AwxmJfrJqkG0BAVMeGJxkR94kamf1auDzeNihg3FKpgxRNCSs0Eyknbu
            6XBqldNxN6zow/KEjQwzUAZozXIjG5L/IA9ArXvNJdp1AnIGE1j0Q0sbbtgekq8W
            mVFh0IrCtIq/
            =ErEd
            -----END PGP MESSAGE-----
          fp: 2F45BC42327907C5B833A93041413E5C18474DDB
    encrypted_regex: ^(data|stringData|addresses)$
    version: 3.11.0
