apiVersion: v1
kind: Secret
metadata:
    name: grafana-oauth
    namespace: monitoring
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:XdcdDmUUpw==,iv:PDZbNbi1B5MRMjLuesGc6odtdo5pNlcr+jhqqeEX0w0=,tag:YkOEsENDcfEfxw7vXMQDAA==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:g3PT0nxJjzeY912VSohgYRrocoFqniSYnF2SYO0Whqw=,iv:ihlgkrjC2UEUauuG6jOo5jYG334aAMx+mT28FBt23AQ=,tag:Y++nyRPMEnCoc8dF5uxsMQ==,type:str]
sops:
    lastmodified: "2026-02-08T13:48:09Z"
    mac: ENC[AES256_GCM,data:doCrI3n3d03j1QV7XYerKddOrkQ1v2DI0Qi31/Zxep9LHEpaxhdZ/tDAWoZDCUKdAsnuRc7O5Sf8ZKAsuD4g1ft+gFb3JqARXDKwi8EZM4K516K/M70drGO/RqjquUW3dDU7GrGsTfosJNvbqrTCSJ/e940pK2JKEoxKvCO5r5o=,iv:QFuz4CtxJ6Y/zAaka5C/l5qzkjpW5VklHfGghx9Bgz4=,tag:GtldAbLJp2S+LJDBjnFM4Q==,type:str]
    pgp:
        - created_at: "2026-02-08T13:48:09Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0FBPlwYR03bAQ//ZifhhjlAof5cwybKModW8FBbqcJ51GWa5pv3CoxFU0E9
            UF4z8FVxujfDg1AtkJ86iwR3/yQB9r87D+kquw1EmjYAsJ5kDfdDjWdkZgTUquFo
            WC1YjoZT7ArucDs7ECfHnCpC/m5YwcmWMTcXleBphXrKSQYsRLv8O0V6BJvRqxu2
            aQmS5+2fsYA+/Qo1fHiM24lqg8UmBSDSJnwNgZIowo/IGkUmxJUp7dvrYGPvk9u0
            PF5HpNEu2HmS4pXlz4tvCDdSDSe9BKQmkqmZ8PDk90yIrMsgzyeDPyLyVDPoHIp9
            vK7mTiDUGohY1Hs6+q8xU3AJvUj2JEdqnt4+IOpHD36gst/I7Uf9yDx5WqNQ4XNJ
            bjq7/abdebRla3uDWulq3DzAJOnl8iLr7P4PHrs1ZcQKZpnMAB09Uloyral06UFg
            KXHvXzBowzG5Wbnxpt6tknKT3yYozht7ACd06djh0hTQxx1UEgdJr9RCua1/zveZ
            0L0MwZVcYhFwuked8VEWHvanyFsvbR4S6he+EMQPzZwv9NBawLr4Ymakb2RIszGK
            Gxs0azj7A+qdX3QeKR/foF3Lw/+SEde5rRD+2NsiwU8G+unJdPNFUFy9KWML/K4S
            I6kuVb7bd7tDwwZFPcRov6sp7AjjH3K3IMbQoRNlJU4VwYRncIRCoFJXUNPsOb7U
            aAEJAhCLbLdWSXBzQFK0OMp20R4DWwz3MbFG6Xkx6Kw7gLRuLa5ZHH8ZvUDxUE9K
            XWC/7KkmTZP0EARInnqX2dRSvLeC6wdkVVgJ6cIkVj1fMWXxYzFbApOUHYoUsTX6
            hx3WkynLUNW1
            =Sg49
            -----END PGP MESSAGE-----
          fp: 2F45BC42327907C5B833A93041413E5C18474DDB
    encrypted_regex: ^(data|stringData|addresses)$
    version: 3.11.0
