apiVersion: v1
kind: ConfigMap
metadata:
  name: crulabs-ca-cert
  namespace: minio
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFqTCCA5GgAwIBAgIUGGBY4BKjCCg6u9qhgi4jdsvYG1cwDQYJKoZIhvcNAQEL
    BQAwZDELMAkGA1UEBhMCREUxDDAKBgNVBAgMA05SVzEOMAwGA1UEBwwFRXNzZW4x
    EDAOBgNVBAoMB0NydUxhYnMxCzAJBgNVBAsMAklUMRgwFgYDVQQDDA9DcnVMYWJz
    IFJvb3QgQ0EwHhcNMjUxMTIzMTcwMzM2WhcNMzUxMTIxMTcwMzM2WjBkMQswCQYD
    VQQGEwJERTEMMAoGA1UECAwDTlJXMQ4wDAYDVQQHDAVFc3NlbjEQMA4GA1UECgwH
    Q3J1TGFiczELMAkGA1UECwwCSVQxGDAWBgNVBAMMD0NydUxhYnMgUm9vdCBDQTCC
    AiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAPXoSY3WpTAAgzKIUA7UWR3K
    ieYXIXtVSAdaNUG660zaBk88uF64T4BGbrz2UhGku6sevWBIMAQ0r2vAZ495Zti6
    nV3w4SmPIzS9D6OyB2Q+J02CUy58/lbupeXBurAFPhWkxUZzqaHYrTxEzPAgmP+E
    rRpkwQhQlFE1+yDlAHAwm0MkIcZ4KeAPorOGDy0gV938C+TxS0maXcqV1pSYtrLi
    GgoClqwLnLhEZN50qcOCzkk3omFH66/MT8OPAEPrUwMd7nWjBWS5OzKgCyX7+2pf
    z82j7WAF/Qnaaajlnm8cgWXSmMdaSPFrsANdSk/JNIs6s0j+TwBMT9lM3XH8HAVy
    zQEgJNzNjTApY33V7OGjTnzkbQOZA/gqrDGIqaTSH9bb/0LkjN4VvCKTeeSpaDjn
    BrjXP8oQ0cI4MmdRFYM/T/ri5bOefp7ajaJOyGkiUFgsz0bQTZRZrEM8LK3UC3XD
    qmxf5s2L48NKBKZ4OynBcFtM7o5nsyUNJ89eAtEJSKLg3Po0k5jAqOCrMlnuyZh9
    SSQtwiSB1Pt0qJJA6MFawnW7hnsAHd7iSddzRw1dLS5SA2Igg8N507qxtFf9Ojtb
    7i9xbEi+qEw/3JMZdtVR6XjiyPV4A5rV0sBbASu9IMBZLRHaOdxXZpf9wOKhvldh
    gyjoRTe1qqyFOrOSERKTAgMBAAGjUzBRMB0GA1UdDgQWBBSMXtpbxgtaLbl8Y9Mq
    6YYvocKaBDAfBgNVHSMEGDAWgBSMXtpbxgtaLbl8Y9Mq6YYvocKaBDAPBgNVHRMB
    Af8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4ICAQAHRgf6CUZ94kS1geTcycPv/g57
    0RN2U3raPX0DUzTf2ZSf7ypW2JqxhIWSX/g7HXLr0aIM3M5Sot2hnQBIZ0bulMbZ
    2Yc7KS+QoVm3kK66Ffwr88y+DIS2hE88PVIvHpPwQY5w9TpldggPRpyzhloMCtVx
    RtboC+u2KPpuaWwvMRN9qa2WvhiLddufryMYpTiAUGAsDSB/UzvSdsxwdDNJU/Jz
    k9ak1pwGr/TYnY0PbyZPKWr5tqA7HckB3tVWGi5xMhdaJIGNPh+sY7PMIC7mFV6C
    Nycgia4OJgTpaxr+6dUuP+UTMTsccIBcmugSJ3g1wVQ7pUXhShjV+ITys/loVitp
    ESiqy4cbNqyKxWHvHvVE4oMXhwBgap1EyrCnOyVha5X3p7mP21CoPeEShhSEfVOD
    Qu3aGolIQyr/8Oj1+wr+x/bm8c6iQQluaWMSXBlsUehOWvbKJDESY7EklVK2QAqt
    yxVM7MFlkGe/Ez7RZB5+aAwTNyR8mQlM+whj+owOJ0mcpMQqalG5OibuWrigLxOp
    Q1dpvlf9ucLvsUV2jtVFMqdWps93jCZxOQjY3s9kh6kfV7kaaNJHryiQemOMyzRL
    yBYGhtqBPmRlKIKNEsGnOzd2/z6ZDudG5mMCGzMhCBw9mKaBtPZH1dBBSNy4lQIQ
    w0N8tq6Y+lzVXiMRug==
    -----END CERTIFICATE-----
