apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - secret.enc.yaml
  - secret_minio-oauth.enc.yaml
  - configmap_ca-cert.yaml
  - helmrelease.yaml
  - httproute.yaml
