apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - cluster-issuer
  - kube-prometheus-stack
  - external-dns
  - ingress-nginx
  - local-path-provisioner
  - kubernetes-dashboard
  - nfs-csi-driver
  - minio
  - loki
  - cloudnative-pg
