apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - cluster-issuer
  - kube-prometheus-stack
  - external-dns
  - gateway-api-crds
  - gateway-api
  - kyverno
  - local-path-provisioner
  - nfs-csi-driver
  - minio
  - loki
  - cloudnative-pg
  - keycloak
  - karma
  - homer
