apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease_postgres.yaml
  - helmrelease.yaml
  - secret_backup-credentials.enc.yaml
  - secret_keycloak-db-credentials.enc.yaml
  - secret_keycloak-credentials.enc.yaml