apiVersion: v1
kind: Service
metadata:
  name: batch
  namespace: batch
spec:
  selector:
    app.kubernetes.io/name: batch
    app.kubernetes.io/instance: batch
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  type: ClusterIP
